### ISSUE TITLE
Is there a Beta "Release channel"?

### ISSUE THREAD

**Issue by GitMurf** [toggl/track-windows-feedback#23]
I see the option for changing to the Beta "Release channel" but when I select it and then close the window and re-open it switches back to the Stable channel. Is there a Beta channel anymore? I know in the past (old app) there was and I was on the Beta channel but not sure if now with new native app if maybe there is only a Stable channel and this dropdown should be ignored?

Thanks!

![image](https://user-images.githubusercontent.com/64155612/206004480-fcfb6b6a-f91e-4014-a096-c02291b02ce1.png)

**Comment by kornelijepetak** [comment]
Since the `8.1.*`, this dropdown's value is ignored and was completely removed in `8.1.5`.

The reason is that we have changed the way we approach the release channels and we have moved to a separate installation for beta (and later dev) release channels. That's the reason why all beta users were implicitly moved to stable.

We are still in the process of reworking all of this and will publish more details and announce this in the future.

If you want to continue participating in our beta program (for which we are very grateful), you will have to install a separate app and for the time being you can do it from here: [Toggl Track Windows BETA](https://toggl.com/track/toggl-desktop/downloads/windows/beta/TogglTrackBeta-windows64.exe.).

This way, there will be no clashes between the stable and the beta app in case something's not working as intended in BETA. 

As for the beta, you should see the `BETA BUILD` title in order to differentiate between various builds.

![image](https://user-images.githubusercontent.com/7033216/208408140-6b5dd166-574a-4a2b-9d3f-5d1611e5de55.png)

**Comment by GitMurf** [comment]
Awesome! Thanks a lot. I will definitely install beta and love the fact can always fall back to stable as a separate installation :)
